"""init

Revision ID: 6071801d1d95
Revises: 20260318_0001
Create Date: 2026-03-19 14:59:46.098825
"""
from alembic import op
import sqlalchemy as sa



revision = '6071801d1d95'
down_revision = '20260318_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_menu', sa.Column('status', sa.Integer(), nullable=False, server_default=sa.text('1')))
    op.add_column('admin_menu', sa.Column('remark', sa.Text(), nullable=True))
    op.add_column('admin_role', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('cms_notice', sa.Column('pinned', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('employee_profile', sa.Column('full_name', sa.String(length=128), nullable=True))
    op.add_column('employee_profile', sa.Column('status', sa.Integer(), nullable=False, server_default=sa.text('1')))
    op.add_column('employee_profile', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('employee_profile', sa.Column('email', sa.String(length=128), nullable=True))
    op.add_column('employee_profile', sa.Column('role_code', sa.String(length=64), nullable=True))
    op.add_column('employee_profile', sa.Column('joined_at', sa.Date(), nullable=True))
    op.add_column('mall_order', sa.Column('receiver_name', sa.String(length=128), nullable=True))
    op.add_column('mall_order', sa.Column('receiver_phone', sa.String(length=32), nullable=True))
    op.add_column('mall_order', sa.Column('items_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('org_department', sa.Column('code', sa.String(length=64), nullable=True))
    op.add_column('org_department', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('org_department', sa.Column('member_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.create_index(op.f('ix_org_department_code'), 'org_department', ['code'], unique=False)
    op.alter_column('admin_menu', 'status', server_default=None)
    op.alter_column('cms_notice', 'pinned', server_default=None)
    op.alter_column('employee_profile', 'status', server_default=None)
    op.alter_column('mall_order', 'items_count', server_default=None)
    op.alter_column('org_department', 'member_count', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_org_department_code'), table_name='org_department')
    op.drop_column('org_department', 'member_count')
    op.drop_column('org_department', 'description')
    op.drop_column('org_department', 'code')
    op.drop_column('mall_order', 'items_count')
    op.drop_column('mall_order', 'receiver_phone')
    op.drop_column('mall_order', 'receiver_name')
    op.drop_column('employee_profile', 'joined_at')
    op.drop_column('employee_profile', 'role_code')
    op.drop_column('employee_profile', 'email')
    op.drop_column('employee_profile', 'phone')
    op.drop_column('employee_profile', 'status')
    op.drop_column('employee_profile', 'full_name')
    op.drop_column('cms_notice', 'pinned')
    op.drop_column('admin_role', 'description')
    op.drop_column('admin_menu', 'remark')
    op.drop_column('admin_menu', 'status')
    # ### end Alembic commands ###
